### ISSUE TITLE
ارور

### ISSUE THREAD

**Issue by amirnabinejad** [FReak4L/Tc-Config#1]
موقع نصب و اجرا ارور میده لطفا راهنمایی کنید،
![IMG_8931](https://github.com/user-attachments/assets/8f5afb1c-b1f7-4cb2-ae2c-cf28c1d07ce2)

**Comment by FReak4L** [comment]
سلام عزیزم نیاز به xanmod kernel داره 
https://t.me/FreakXray/22
این آموزش اجراس
